### ISSUE TITLE
Cannot start docker container

### ISSUE THREAD

**Issue by fraggom** [VibeNL/GhostfolioSidekick#129]
Hi everyone,

I am running into issues starting the docker container. It failed due to issues with the bind mounts and I couldn't find a solution. Logs say

`Microsoft.Extensions.Hosting.Internal.Host Unhandled exception. System.UnauthorizedAccessException: Access to the path ...  is denied.`

My compose looks the following:

```
version: '3.9'
services:
  ghostfoliosidekick:
    image: vibenl/ghostfoliosidekick
    container_name: ghostfolio-sidekick
    networks:
      - ghostnet
    volumes:
      - /volume1/docker/ghostfoliosidekick/config:/gfsk/config
      - /volume1/docker/ghostfoliosidekick/import:/gfsk/import
    environment:
      GHOSTFOLIO_URL: ghostfolio-app:3333
      GHOSTFOLIO_ACCESTOKEN: abc
      FILEIMPORTER_PATH: /gfsk/import
      CONFIGURATIONFILE_PATH: /gfsk/config
  
networks:
  ghostnet:
    name: dockernet
    external: true
```
I was trying different destinations but always the same result. I was as well trying to start the container with user flags, but didn't work as well. Maybe you have an idea? thanks!
